### ISSUE TITLE
No output config parameter set during benchmark run

### ISSUE THREAD

**Issue by patrickwestphal** [AKSW/SML-Bench#8]
It seems, currently the `output` config option is not set by the benchmark runner resulting in errors like this in the (Prolog systems') `run` scripts:

```
Traceback (most recent call last):
  File "./run", line 284, in <module>
    output_file = cfg['output']
KeyError: 'output'
```

**Comment by giuseta** [comment]
The problem was in line 17 of org.aksw.mlbenchmark.systemrunner.CrossValidationStep.java. A private field was hiding an inherited field.

**Comment by patrickwestphal** [comment]
Thanks a lot @giuseta ! :)
